# -*- coding: utf-8 -*-
"""CursoPythonLinkedin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T50WeySxX__YDKgG6cY2SDS9pwDwz-fv

Hello World
"""

print("hello world")

"""Variables"""

wallet = 50

print("quantidade de dinheiro = ", wallet)

wallet = wallet - 12

print("quantidade de dinheiro = ", wallet)

date = 3

print("dia de hoje é: ", date)

"""Numbers"""

day = 21

temp = -15

weight = 68.6988

print(3+6)

print(day + 2)

print(temp * 2)

"""string"""

brenda = 'amorzin'

print("a Brenda é meu ", brenda)

movie = 'fate'

print(movie)

"""boolean"""

day = 21
month = 'October'
temp = 20
day_name = 'wednesday'
weight = 68.65
light_is_on = False

if light_is_on:
  print("the light is on")
  print('nice')
print(f"Today is {day_name}, {month} {day} and its {temp} degrees outside")

computer_on = True

if computer_on:
  print('legal')

"""Else"""

light_is_on = False

if light_is_on:
  print("the light is on")
  print('nice')
else:
  print('its dark')

weight = 68.76

if weight < 68:
  print('boa')
else:
  print('sadge')


age = 15

if age >= 18:
  print('adult')
else:
  print('child')

"""Random"""

import random

print(random.randint(1,10))

print(random.random())

i = random.randint(1,3)
print(i)

if i == 1:
  print('yes')
elif i == 2:
  print('no')
else:
  print('maybe')

"""Fortune Cookie"""

import random

numero_sorte = random.randint(1,100)

fortune_num = random.randint(1,3)

fortune_txt = ''

if fortune_num == 1:
  fortune_txt = 'otimo'
elif fortune_num == 2:
  fortune_txt = 'normal'
else:
  fortune_txt = 'pessimo'



print(f"Você tera um dia {fortune_txt}! Seu numero da sorte é {numero_sorte}")

"""lists"""

fav = ['fate', 'dota', 'brenda', 'choco']

print(fav[0])

"""add, insert, remove"""

fav = ['fate', 'dota', 'brenda', 'choco']

print(len(fav))

fav.append('comer')

print(len(fav))

print(fav)

fav.insert(2,'nice')

print(fav)

del(fav[2])

print(fav)

"""For"""

for number in range(10):
  print('hello')
  print('nice')
  print(number)

fav = ['fate', 'dota', 'brenda', 'choco']

for favo in fav:
  print(favo)

for number1 in range(40):
  print((number1 + 1) * 2)

"""Dicionarios"""

dogs = {'Jane': 6,'Tom': 14,'choco': 3}

print(dogs['choco'])

dogs['fofo'] = 2

print(dogs)

del(dogs['Tom'])

print(dogs)

"""splitting string"""

text = """ PCMS: Publicados novos editais do concurso para o cargo de delegado
 - 31 janeiro 2022.
  As Secretarias de Administração e Desburocratização (SAD)
   """

print(text)
print(text.split())
print(len(text.split()))

"""contando palavras"""

text = """
Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.

Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this.

But, in a larger sense, we can not dedicate—we can not consecrate—we can not hallow—this ground. The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced. It is rather for us to be here dedicated to the great task remaining before us—that from these honored dead we take increased devotion to that cause for which they gave the last full measure of devotion—that we here highly resolve that these dead shall not have died in vain—that this nation, under God, shall have a new birth of freedom—and that government of the people, by the people, for the people, shall not perish from the earth.
"""

print(text.split())

word_count = {}

for word in text.lower().split():
  if word in word_count:
    word_count[word] += 1
  else:
    word_count[word] = 1

  

print(word_count)

"""Function"""

def bark():
  print("woof woof!")
  print("dog dogu")

bark()
bark()
bark()

for x in range(10):
  bark()

def hello():
  print('hello nick!')

hello()

"""Parameters"""

def hello(name):
  print(f"Hello {name}!")

hello("John")

def add_numbers(num1,num2):
  print(num1 + num2)

add_numbers(4,7)

def dog_info(dog_age, dog_name):
  print(f"o nome do dog é {dog_name}, ele tem {dog_age} anos")

dog_info(3, "choco")

"""Return"""

def double(number): #dobra os numero
  return number * 2

new_number = (double(5))      #novo numero dobrado

print(new_number)     #imprime o numero dobrado

def upper(frase):
  return frase.upper()    #mete aquele maiusculo

print(upper('tudo maiusculo'))

names = ['uma', 'duas', 'tres']

for name in names:
  print((upper(name)))

"""Input"""

user_txt = input('Enter some text')

print(user_txt)

user_number = input('What do you want to double?')

print(int(user_number) * 2)

txt = input('texto para modificar')
x = input('escreva 1 para maiusculo e 2 para minusculo')

if int(x) == 1:
  print(txt.upper())
else:
  print(txt.lower())

"""Number Guesser"""

import random
import time

print('Bem vindo ao jogo do chute, chute loucamente um numero entre 1 e 100')
time.sleep(3)
print('escolhendo um numero...')
time.sleep(2)
guess = int(input('de um chute entre 1 e 100:'))
correct_number = random.randint(1,100)
guess_count = 1

while guess != correct_number:
  time.sleep(1)
  guess_count += 1
  if guess < correct_number:
    print('Errado!!! \nTente um numero maior')
    guess = int(input('de um chute entre 1 e 100:'))
  else:
    print('Errado!!! \nTente um numero menor')
    guess = int(input('de um chute entre 1 e 100:'))


print(f"Acertou!! \no Numero certo é {correct_number} \nVocê chutou {guess_count} vezes")